sonar.projectKey=aceest-fitness-api
sonar.projectName=ACEest Fitness API
sonar.projectVersion=3.2.4

sonar.sources=.
sonar.tests=tests
sonar.inclusions=app.py,scripts/**/*.py
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**,**/*.db,allure-results/**,test-results/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=test-results/coverage.xml
sonar.sourceEncoding=UTF-8
