apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-api
  namespace: aceest
  labels:
    app: aceest-fitness-api
spec:
  type: NodePort
  selector:
    app: aceest-fitness-api
    track: stable
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080
